export const SHEET_SCHEMAS = {
  GIMNASIOS: [
    "ID",
    "NOMBRE",
    "DIRECCION",
    "TELEFONO",
    "LOGO_URL",
    "COLOR_PRIMARIO",
    "COLOR_SECUNDARIO",
    "COLOR_FONDO",
    "ESTADO",
    "FECHA_ALTA",
  ],
  SUCURSALES: [
    "ID",
    "GYM_ID",
    "NOMBRE",
    "DIRECCION",
    "QR_TOKEN",
    "ESTADO",
    "FECHA_ALTA",
  ],
  USUARIOS: [
    "ID",
    "GYM_ID",
    "BRANCH_ID",
    "MEMBER_ID",
    "NOMBRE",
    "EMAIL",
    "PASSWORD_HASH",
    "ROL",
    "ESTADO",
    "PROVEEDOR",
    "GOOGLE_SUB",
    "FECHA_ALTA",
  ],
  ACTIVIDADES: ["ID", "GYM_ID", "NOMBRE", "ACTIVA"],
  MAQUINAS: [
    "ID",
    "GYM_ID",
    "NOMBRE",
    "CATEGORIA",
    "IMAGEN_URL",
    "IMAGEN_ORIGEN",
    "ACTIVA",
    "FECHA_ALTA",
  ],
  SOCIOS: [
    "ID",
    "GYM_ID",
    "BRANCH_ID",
    "NOMBRE",
    "EMAIL",
    "TELEFONO",
    "DOCUMENTO",
    "ESTADO",
    "PLAN_ID",
    "FECHA_ALTA",
    "FECHA_VENCIMIENTO",
    "OBSERVACIONES",
  ],
  PLANES: ["ID", "GYM_ID", "NOMBRE", "PRECIO", "DURACION_DIAS", "ESTADO"],
  PAGOS: [
    "ID",
    "GYM_ID",
    "BRANCH_ID",
    "MEMBER_ID",
    "PLAN_ID",
    "FECHA",
    "MONTO",
    "METODO",
    "OBSERVACIONES",
    "RECEPTIONIST_ID",
    "NUEVA_FECHA_VENCIMIENTO",
  ],
  INGRESOS: [
    "ID",
    "GYM_ID",
    "BRANCH_ID",
    "MEMBER_ID",
    "FECHA",
    "HORA",
    "RESULTADO",
    "MOTIVO",
  ],
} as const;

export type SheetName = keyof typeof SHEET_SCHEMAS;
